### ISSUE TITLE
Fast+cleanly fail on missing: `cs`, `hub` or `jq`

### ISSUE THREAD

**Issue by dwijnand** [dwijnand/scala-runners#1]

**Comment by dwijnand** [comment]
Mitigated Homebrew-side by declaring it as a dependency: https://github.com/dwijnand/homebrew-formulas/commit/0e2bbf0ad2def7f155724d2d3c3840ce80ee114c.

**Comment by retronym** [comment]
And on `hub` ?

**Comment by dwijnand** [comment]
Yep, now that too.

**Comment by dwijnand** [comment]
`jq` too

**Comment by d-ogxwx** [comment]
@dwijnand Can I take this? I had been doing some trials on this.

**Comment by dwijnand** [comment]
Sure!

**Comment by d-ogxwx** [comment]
@dwijnand Thank you!

**Comment by d-ogxwx** [comment]
I accidentally pressed the unassign button!

**Comment by dwijnand** [comment]
We now have checks to fail fast and clearly.
