### ISSUE TITLE
Startup time comparison

### ISSUE THREAD

**Issue by dwijnand** [dwijnand/scala-runners#2]
There's a performance regression in startup time compared to the original implementation:

```
15:59:59 $ time /usr/local/opt/scala@2.13/libexec/bin/scala -help 2> /dev/null

real	0m0.479s
user	0m0.652s
sys	0m0.074s

16:00:12 $ time /usr/local/opt/scala@2.13/libexec/bin/scala -help 2> /dev/null

real	0m0.468s
user	0m0.652s
sys	0m0.071s

16:00:13 $ time scala -help 2> /dev/null

real	0m1.977s
user	0m3.569s
sys	0m0.246s

16:00:27 $ time scala -help 2> /dev/null

real	0m2.030s
user	0m3.783s
sys	0m0.251s

16:00:29 $ coursier bootstrap scala -f
Wrote /d/scala-runners/scala

16:00:34 $ time ./scala -help 2> /dev/null

real	0m0.837s
user	0m1.251s
sys	0m0.132s

16:00:37 $ time ./scala -help 2> /dev/null

real	0m0.839s
user	0m1.268s
sys	0m0.137s

16:00:39 $ coursier bootstrap --standalone scala -f
Wrote /d/scala-runners/scala

16:00:43 $ time ./scala -help 2> /dev/null

real	0m0.947s
user	0m1.641s
sys	0m0.155s

16:00:45 $ time ./scala -help 2> /dev/null

real	0m0.960s
user	0m1.665s
sys	0m0.159s
```

Summary:
* original: ~0.5s
* coursier launch: ~2s
* coursier boostrap: ~0.8s
* coursier bootstrap --standalone: ~1s

**Comment by dwijnand** [comment]
@alexarchambault any ideas or suggestions as to how to improve this?

**Comment by alexarchambault** [comment]
Yes, I forgot to mention it yesterday. Native images of the coursier CLI can be generated with graal. The coursier `launch` command will need to be tweaked to work from the native image though (it should spawn a JVM instead of loading the app to be launched in its JVM).

You should be able to generate a coursier graalvm native image with
```
$ coursier install coursier-graalvm
```
`GRAALVM_HOME` needs to be set. I'm using graal `1.0.0-rc16`, I'm not sure the latest versions work fine (some options need to be tweaked I think).

I'll also probably push pre-built images as github release assets.

**Comment by alexarchambault** [comment]
The graalvm launcher would probably start the app it launches the same way as the former bash scripts from the scala distribution (calling `java -cp … main.class`). The only overhead will come from the native app, so I would expect it to be minimal (less than the ~300 ms of the bootstrap).

**Comment by dwijnand** [comment]
But does it make sense that `coursier launch scala` is taking 1.5s to fetch scala-compiler + dependencies (which are already present on disk), find its main class and launch it, and then 0.5s to launch enough of `scala.tools.nsc.MainGenericRunner` to process `-help` and exit?

Should, maybe, `coursier launch` (or underlying pieces) cache and uncache that data in `~/Library/Cache/Coursier`, so it's only 2s the first time and much quicker after?

**Comment by alexarchambault** [comment]
I tried that kind of things in the past, but it ended up not bringing much gains IIRC. Caching done right needed a number of classes to have been classloaded upfront too, and adds its own logic, all running on a cold JVM.

**Comment by alexarchambault** [comment]
Things are much faster on a warm JVM:
```
$ coursier fetch org.scala-lang:scala-compiler:2.13.0 --benchmark 20
Warm-up 1 / 20
330 ms
Warm-up 2 / 20
61 ms
Warm-up 3 / 20
41 ms
…
Warm-up 16 / 20
33 ms
Warm-up 17 / 20
33 ms
Warm-up 18 / 20
31 ms
Warm-up 19 / 20
37 ms
Warm-up 20 / 20
31 ms
Benchmark resolution
28 ms
…
```

**Comment by alexarchambault** [comment]
Maybe nailgun could be useful, for that kind of uses.

**Comment by dwijnand** [comment]
Yeah, been separately chatting with @jvican about if/how Bloop could hold the warm compiler+repl classes and spin up a fresh instance.

**Comment by alexarchambault** [comment]
You mean, re-using the JVM of bloop to run scalac? If not, coursier-graalvm is probably your best bet medium term (once I manage to automatically push pre-built native images to github, I'll probably make `coursier install coursier` install the native image).

**Comment by dwijnand** [comment]
Yeah something like that, but it's tangled with issues of jline/readline.

I look forward to installing a native coursier. :) And perhaps we can call this issue resolved with that

**Comment by dwijnand** [comment]
> The graalvm launcher would probably start the app it launches the same way as the former bash scripts from the scala distribution (calling `java -cp … main.class`). The only overhead will come from the native app, so I would expect it to be minimal (less than the ~300 ms of the bootstrap).

Turns out to be about 370ms, but I feel like that's good enough to close this off:

```
$ time /usr/local/opt/scala/libexec/bin/scala -help 2> /dev/null

real	0m1.002s. <-- not sure why
user	0m0.825s
sys	0m0.151s
$ time /usr/local/opt/scala/libexec/bin/scala -help 2> /dev/null

real	0m0.490s
user	0m0.700s
sys	0m0.092s
$ time /usr/local/opt/scala/libexec/bin/scala -help 2> /dev/null

real	0m0.489s
user	0m0.697s
sys	0m0.092s
$ time /usr/local/opt/scala/libexec/bin/scala -help 2> /dev/null

real	0m0.490s
user	0m0.706s
sys	0m0.093s
$ time scala -help 2> /dev/null

real	0m1.894s. <-- first fetch of coursier/apps of the day, I think
user	0m1.368s
sys	0m0.184s
$ time scala -help 2> /dev/null

real	0m0.877s
user	0m1.339s
sys	0m0.139s
$ time scala -help 2> /dev/null

real	0m0.873s
user	0m1.342s
sys	0m0.137s
$ time scala -help 2> /dev/null

real	0m0.882s
user	0m1.352s
sys	0m0.145s
```

**Comment by alexarchambault** [comment]
I've been seeing those periodic longer resolutions too… Should be easy to fix hopefully: https://github.com/coursier/coursier/issues/1738.
