### ISSUE TITLE
To aid `git bisect` of Scala regressions, support taking Scala version from head SHA of current checkout

### ISSUE THREAD

**Issue by SethTisue** [dwijnand/scala-runners#36]
So after `git bisect good` or `git bisect bad` in scala/scala takes me to a new SHA, you want to do `scala --scala-version 2.13.5-bin-abcd123-SNAPSHOT`, where abcd123 is the commit the bisect currently has me at.

**Comment by SethTisue** [comment]
closing as this seems like a really niche feature and anyway scala-cli is the new hotness

**Comment by dwijnand** [comment]
How does scala-cli do this for you?

**Comment by SethTisue** [comment]
It doesn’t, but it seems too niche to me to expect either project to do, it seems like something you’d put in a bisect script instead, rather than expecting support upstream.
