### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by SethTisue** [dwijnand/scala-runners#37]

**Comment by SethTisue** [comment]
This is done, but existing homebrew users will likely hit `fatal: Remote branch master not found in upstream origin` when they `brew update`

When this occurs, here's what to do:

```
brew update
brew uninstall scala-runners
rm -fr ~/Library/Caches/Homebrew/scala-runners--git/
brew install --HEAD scala-runners
```

**Comment by dwijnand** [comment]
https://github.com/dwijnand/scala-runners/commit/aa559b556a3eebfec82e8083acb306ad2c5c022f
