### ISSUE TITLE
Linux install instructions

### ISSUE THREAD

**Issue by SethTisue** [dwijnand/scala-runners#38]
Dale has made it convenient for Mac users to install this via homebrew, but what about Linux?

Is it just a matter of copying the scripts into some directory on the PATH?

related: Windows ticket (#4)

**Comment by dwijnand** [comment]
Yep.  There's Linuxbrew too, so probably can either use my formula or derive from it.

**Comment by SethTisue** [comment]
fyi @bjornregnell

**Comment by bjornregnell** [comment]
thnx @SethTisue @dwijnand Although Linuxbrew is cool, it's yet another dependency and thus for a beginner another step to figure out, so I think it would be best to have some kind of install solution that works with a command or a click without installing anything else.

**Comment by SethTisue** [comment]
Yeah. In the long run, any beginner-friendliness will need to come from the efforts of Scala Center + VirtusLab. I hope that those folks'll look at this repo and perhaps take some inspiration from it, but for now this remains a kind of under-the-radar effort that primarily interests people who need to run lots of different Scala versions (including nightlies and PR validation builds), so that mainly means Scala contributors.

**Comment by dwijnand** [comment]
Yeah, I'd initially wanted these runners to replace the ones we'd historically had in the Scala project, using Coursier's app launching capabilities.  But then steam seem to run out on that front, and interest wandered to other things.

I don't know of any linux built in command or click that does the basic "download something and stick it on your path".  I'm not keen to implement a bash script to start instructing a `curl ... | bash`-like setup.  I guess something along the lines of "Download https://github.com/dwijnand/scala-runners/archive/refs/heads/main.zip and stick it on your PATH" might work for some users?

**Comment by bjornregnell** [comment]
@dwijnand Yes for some users that would definately work. For example Ammonite [is installed with a curly one-liner](https://ammonite.io/#InstallationonLinux). Copy-pasting into terminal is ok for most if not all linux users (but beginners of course need to learn to reflect on who to trust...).  For windows a single click exe, or even better msi, is da thing, I guess. And I think you can't even count on curl being there in windows powershell/cmd.

@SethTisue A Scala Center official solution is the way to go, but in the mean time **is a link to this repo ok to spread?** I mean: how much "under the radar" do you want this to be at its current stage? (I'm e.g. thinking of the recent question on `cs list` in gitter/coursier. There regularly comes questions there and elsewhere on coursier's current limitations, so this repo might already help people get them a runner working... 

I think it would be really nice with a bash-compatible one-liner that "just works" in Ubuntu/Debian in the instructions of this repo that places the executables in the current directory (and people can decide if they put it in their bin or whatever for now). Would that be possible? 

(I tried to look at the brew recepies but I have no clue how they work, so I'm still unsure how to get the runners going on my ubuntu box - you mean I can just download the single `scala-runner` script file and create the symbolic links myself and it will work (given that the symlinks are found via my path)?)

**Comment by dwijnand** [comment]
> For windows a single click exe, or even better msi, is da thing, I guess. And I think you can't even count on curl being there in windows powershell/cmd.

Yeah, that's a PITA and I don't think I want to take that on.

> @SethTisue A Scala Center official solution is the way to go, but in the mean time **is a link to this repo ok to spread?** I mean: how much "under the radar" do you want this to be at its current stage? (I'm e.g. thinking of the recent question on `cs list` in gitter/coursier. There regularly comes questions there and elsewhere on coursier's current limitations, so this repo might already help people get them a runner working...

I regularly link to this in the context of compiler contributors, who might find it handy, so it's not a secret project.  But I would also encourage beginners to set up their IDE as well as start to understand sbt...

> I think it would be really nice with a bash-compatible one-liner that "just works" in Ubuntu/Debian in the instructions of this repo that places the executables in the current directory (and people can decide if they put it in their bin or whatever for now). Would that be possible?
> 
> (I tried to look at the brew recepies but I have no clue how they work, so I'm still unsure how to get the runners going on my ubuntu box - you mean I can just download the single `scala-runner` script file and create the symbolic links myself and it will work (given that the symlinks are found via my path)?)

Looks like this works:

```bash
curl -sSLO https://github.com/dwijnand/scala-runners/archive/refs/heads/main.zip && unzip main.zip scala-runners-main/scala* && mv scala-runners-main/scala* . && rm -r scala-runners-main main.zip
```

**Comment by SethTisue** [comment]
> is a link to this repo ok to spread?

My personal take is: I wouldn't (I don't) recommend it to beginners. There are too many caveats.  But otherwise fine to spread as long as it's clear it's an experimental alternative

**Comment by bjornregnell** [comment]
Your curly one-liner worked fine! @dwijnand   Should that be in the README for linux install? That'd be ok by me. Really nice that I can start the latest release with just  `scala -3.0.2-RC1` !  
But these did not work: neither `scala -3.0.next`  nor `scala -3.0.head`. However `scala -2.13.next` *does* work, although not `./scala -2.13.head`.

**Comment by bjornregnell** [comment]
BTW: on a new Windows 10 install that I have on a dual boot laptop Windows 10 seems to have `curl` and `tar` out of the box (but not unzip).

**Comment by dwijnand** [comment]
> Your curly one-liner worked fine! @dwijnand Should that be in the README for linux install? That'd be ok by me. Really nice that I can start the latest release with just `scala -3.0.2-RC1` !

I'll add it.

> But these did not work: neither `scala -3.0.next` nor `scala -3.0.head`.

That's because, as opposed to Scala 2.13/2.12/..., it's `-3.next` and `-3.head`.

> However `scala -2.13.next` _does_ work, although not `./scala -2.13.head`.

What happened with `-2.13.head` then?

**Comment by bjornregnell** [comment]
```
$ ./scala -2.13.head
Aborting: Failed to set scala version given arg 2.13.head
```

**Comment by bjornregnell** [comment]
```
$ ./scala -3.next
./scala: line 72: hub: command not found
./scala: line 72: jq: command not found
Aborting: Failed to set scala version given arg 3.next
```
-3.head worked fine.

**Comment by SethTisue** [comment]
`-2.13.head` should be working. if it still isn't working for you, please open a separate ticket

as for `hub` and `jq` "command not found" errors, that's https://github.com/dwijnand/scala-runners/issues/1 but since that might not progress anytime soon, a PR improving the documentation on this would be welcome since non-Homebrew users are especially likely to hit it

**Comment by dwijnand** [comment]
-2.13 is the same as the others, it's just missing checkHub call.  I'll makes some tweaks.

**Comment by dwijnand** [comment]
7877e10 (and f71085c and 05798b9):

```bash
$ brew unlink coursier hub jq
Unlinking /usr/local/Cellar/coursier/2.0.13... 3 symlinks removed.
Unlinking /usr/local/Cellar/hub/2.14.2... 33 symlinks removed.
Unlinking /usr/local/Cellar/jq/1.6... 8 symlinks removed.
$ ./scala -2.13.6
cs command required
$ ./scala -2.13.head
Failed to set scala version given the argument '2.13.head', cause: hub command required
$ ./scala -3.next
Failed to set scala version given the argument '3.next', cause: jq command required
```

**Comment by dwijnand** [comment]
Added to the README: bd6c830
