### ISSUE TITLE
Scala 3 / Dotty support

### ISSUE THREAD

**Issue by SethTisue** [dwijnand/scala-runners#8]
nuff said

**Comment by SethTisue** [comment]
Martin asked about this at the Scala meeting today. I assume (perhaps naively 😁) there's no fundamental barrier, just "if 2 this main class name, else that main class name" type stuff.

**Comment by dwijnand** [comment]
`scala-runner` doesn't really do main classname things itself, but uses the app coursier's app definitions.  `scalac` means https://github.com/coursier/apps/blob/master/apps/resources/scalac.json.  There is a https://github.com/coursier/apps/blob/master/apps/resources/dotty-repl.json.

So perhaps the steps to resolve this is PR coursier/apps for dotc and dotd, and then add symlinks & some bash code to wire dotr/dotc/dotd to those 3.

There's also the equivalent of `scalap`, should that be `dotp`?  What about the one that prints TASTY?  Looks like in the dotty distribution those are options of `dotc`: https://github.com/lampepfl/dotty/blob/bb52aa84c0483dd3654f1b3ecaabe16a90783897/dist/bin/dotc#L87-L91.

**Comment by SethTisue** [comment]
no idea about `scalap`

"mm hmm" to the rest of your comment, but also, I was thinking ahead to `scala -30` since that day is not so far off, really. the existence of `dotc` and friends is temporary, so maybe now is not too soon to just unify them in this context?

**Comment by dwijnand** [comment]
Sure, we can try to make `scala{,c,doc,p} -30` give equivalents for the Dotty implementations, under the understanding that that stuff is more experimental than the -2 things.

Btw, just a few days ago, before you'd joined the fun here: https://github.com/dwijnand/scala-runners/commit/59a94d8c687e546a2ecf3a15b09062d6c0e3d2cf 😄.

**Comment by SethTisue** [comment]
related: https://github.com/d-ogxwx/dvm cc @d-ogxwx

**Comment by SethTisue** [comment]
this could probably wait until Scala 3.0.0-M1 is released (possibly as soon as a month from now, remains to be seen), since (according to @anatoliykmetyuk) M1 is when the artifact naming will change (dotty->scala3, ch.epfl.lamp -> org.scala-lang) as well as the script naming (bye bye `dotc`/`dotr`)

I mean, unless you want the runners to also support historical Dotty versions. which would be pretty cool actually... but it's less important than getting on board the 3.0 train

**Comment by d-ogxwx** [comment]
@SethTisue Thank you for reporting😄.

**Comment by d-ogxwx** [comment]
I have created sample code to support the scala3(dotty) version. And I would like to add this enhancement (in scala-runners).

https://github.com/d-ogxwx/scala-runners-sample-i8

**Comment by dwijnand** [comment]
@d-ogxwx Send a PR, I'd be happy to look at the details with you and hear your thought process.

**Comment by dwijnand** [comment]
Looks like there are new coursier app descriptors for scala 3:

```
s3='cs launch scala3-repl --' and sc3='cs launch scala3-compiler --'
```

**Comment by lrytz** [comment]
Note that the `scala3-repl` app always launches the repl ([it runs `dotty.tools.repl.Main`](https://github.com/coursier/apps/blob/master/apps/resources/scala3-repl.json)), so it doesn't work as a runenr to start a compiled program. https://github.com/coursier/coursier/issues/2058

The `scala` app [runs `scala.tools.nsc.MainGenericRunner`](https://github.com/coursier/apps/blob/master/apps/resources/scala.json), which then either starts the repl or runs the argument program.

**Comment by SethTisue** [comment]
to do list:

* versions:
  * [x] --scala-version ...
  * [x] -3
  * [x] -3.0.2-RC1  # and similar
  * [x] -3.head
  * [x] -3.next
    * this should be.... the current RC, I guess?
* apps
  * [x] scalac
  * [x] repl
  * [ ] app/object runner
    * waiting on https://github.com/lampepfl/dotty/pull/13081
  * [ ] script runner
    * waiting on https://github.com/lampepfl/dotty/pull/13081
  * [x] scaladoc
    * should work after https://github.com/coursier/apps/pull/106 is merged
  * [x] scala3-decompiler
  * [x] ~scalap~ N/A

**Comment by SethTisue** [comment]
Cowboy Dale has pushed basic support to master 🤠 

```
* 4880afe - Fix tests (71 minutes ago) <Dale Wijnand>
* 930df03 - Add scaladoc + scalap support too for scala 3 (2 hours ago) <Dale Wijnand>
* 9b60e00 - Support "./scalac -3.0.2-RC1" (3 hours ago) <Dale Wijnand>
* e930d13 - Implement -3.head (3 hours ago) <Dale Wijnand>
* 3c46750 - Initial scala 3 REPL support (3 hours ago) <Dale Wijnand>
* 53cfcb4 - Initial scala 3 compiler support (3 hours ago) <Dale Wijnand>
```

**Comment by SethTisue** [comment]
and now `-3.next` works: 3cb6c70b8ee1cc6bb304a0375b626a4e92299b44

**Comment by SethTisue** [comment]
so this is mostly done, but leaving it open until after https://github.com/lampepfl/dotty/pull/13081 lands

**Comment by SethTisue** [comment]
13081 landed, so `scala -3.head` works now 🎉, and I have been using it just about every day

**Comment by SethTisue** [comment]
@dwijnand (at least, I think this now counts as done?)

**Comment by dwijnand** [comment]
We still need a coursier app to use that new main (and potentially tweak it for more "vs scala 2's GenericMain" differences)

**Comment by dwijnand** [comment]
> We still need a coursier app to use that new main (and potentially tweak it for more "vs scala 2's GenericMain" differences)

Fixed in https://github.com/dwijnand/scala-runners/commit/949a867ea39430c354d948f8198486942ffb6132

**Comment by SethTisue** [comment]
yay! working for me so far
