### ISSUE TITLE
may I use this code? :)

### ISSUE THREAD

**Issue by hrhino** [dwijnand/scala-runners#9]
Which is to say, please do add a LICENSE somewhere...

**Comment by SethTisue** [comment]
Wijnand MegaIndustries Ltd's enterprise sales team will be in touch

**Comment by hrhino** [comment]
I have at least 1,000,000 micro-users hoping for a license; do I qualify for bulk rates?

**Comment by SethTisue** [comment]
you can probably negotiate a small discount on the usage charges you've already racked up

here's a picture of the sales rep who will be phoning you shortly:

<img width="299" alt="Screen Shot 2020-03-25 at 7 31 46 PM" src="https://user-images.githubusercontent.com/161079/77604312-6b8e6080-6ecf-11ea-95d0-f5e96d8729f7.png">

**Comment by dwijnand** [comment]
After lots of complaints about wanting to make meow money, she accepted to license this as Apache 2.0:

* https://github.com/dwijnand/scala-runners/commit/8110294ffa3cefff05a0e415bbcbe5fdec8cef47
* https://github.com/dwijnand/scala-runners/commit/e6996f8a215905a452568d3fa774d379062b054a
